name: abliteration
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - black
  - python=3.11
  - pip:
    - einops 
    - tiktoken 
    - jaxtyping
    - ipykernel
    - IProgress 
    - ipywidgets
    - jupyterlab
    - flash-attn
    - accelerate
    - transformers 
    - scikit-learn
    - transformer_lens 
    - transformers_stream_generator 
