name: abliteration
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - black
  - python=3.11
  - pip:
    - -i https://pypi.tuna.tsinghua.edu.cn/simple
    - einops 
    - tiktoken 
    - jaxtyping
    - ipykernel
    - IProgress 
    - ipywidgets
    - jupyterlab
    - transformers 
    - scikit-learn
    - transformer_lens 
    - transformers_stream_generator 
